-- Jalankan sekali dalam Supabase > SQL Editor.
-- Jadual ini hanya membenarkan tetamu membaca dan menambah ucapan.
-- Tetamu tidak diberi kebenaran mengubah atau memadam ucapan.

create table public.wishes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 50),
  message text not null check (char_length(message) between 3 and 240),
  created_at timestamptz not null default now()
);

alter table public.wishes enable row level security;

create policy "Ucapan boleh dibaca umum"
on public.wishes
for select
to anon
using (true);

create policy "Tetamu boleh menghantar ucapan"
on public.wishes
for insert
to anon
with check (
  char_length(name) between 2 and 50
  and char_length(message) between 3 and 240
);
